import { createSupabaseServerClient } from "@/lib/supabase";
import type { AutomationSettings, NoticeLog, NoticeRule, NoticeTemplate, WorkflowEvent, WorkflowRun } from "@/types";

type NoticeTemplateRow = { id: string; organization_id: string | null; template_key: string; category: string | null; notice_type: string | null; subject: string; body: string; status: string | null; timing_rule: string | null; recipient_rules: Record<string, unknown> | null; variables: string[] | Record<string, unknown> | null; created_at: string; updated_at: string; };
type NoticeRuleRow = { id: string; organization_id: string; rule_key: string; enabled: boolean; trigger_type: string; timing_offset: number; timing_unit: string; template_id: string | null; recipient_behavior: string; filters: Record<string, unknown> | null; created_at: string; updated_at: string; notice_templates?: { template_key: string } | null; };
type NoticeLogRow = { id: string; organization_id: string; notice_type: string; template_id: string | null; rule_id: string | null; buyer_id: string | null; puppy_id: string | null; related_type: string | null; related_id: string | null; scheduled_at: string | null; sent_at: string | null; delivery_status: string; failure_reason: string | null; provider: string | null; provider_message_id: string | null; dedupe_key: string | null; created_at: string; updated_at: string; };
type WorkflowRunRow = { id: string; organization_id: string; run_key: string; status: string; started_at: string | null; finished_at: string | null; summary: Record<string, unknown> | null; created_at: string; updated_at: string; };
type WorkflowEventRow = { id: string; organization_id: string; run_id: string | null; event_key: string; event_type: string; related_type: string | null; related_id: string | null; status: string; payload: Record<string, unknown> | null; created_at: string; };
type AutomationSettingsRow = { id: string; organization_id: string; notices_enabled: boolean; payment_notices_enabled: boolean; document_notices_enabled: boolean; transportation_notices_enabled: boolean; puppy_milestone_notices_enabled: boolean; provider_name: string; from_email: string | null; reply_to_email: string | null; quiet_hours: Record<string, unknown> | null; created_at: string; updated_at: string; };

export type AutomationWorkspaceData = { templates: NoticeTemplate[]; rules: NoticeRule[]; logs: NoticeLog[]; workflowRuns: WorkflowRun[]; workflowEvents: WorkflowEvent[]; settings: AutomationSettings | null; };
export const noticeVariables = ["breeder_name", "buyer_name", "puppy_name", "litter_name", "amount_due", "balance", "due_date", "transport_date", "document_title", "status"];

const defaultTemplates: NoticeTemplate[] = [template("payment-reminder", "Payment Reminder", "payment_reminder", "Upcoming payment for {{puppy_name}}", "Hi {{buyer_name}}, your next payment of {{amount_due}} is scheduled for {{due_date}}. Your current balance is {{balance}}."), template("document-ready", "Document Ready", "document_ready", "{{document_title}} is ready", "Hi {{buyer_name}}, {{document_title}} is ready in your buyer file."), template("puppy-update", "Puppy Update", "puppy_update", "{{puppy_name}} update", "Hi {{buyer_name}}, {{puppy_name}} has a new update from {{breeder_name}}.")];
const defaultRules: NoticeRule[] = [rule("payment-due", "Payment Reminder", "payment_due", -3, "payment-reminder", { requires_balance: true }), rule("document-ready", "Document Ready", "document_ready", 0, "document-ready", { buyer_required: true }), rule("puppy-update", "Puppy Update", "puppy_update", 0, "puppy-update", { buyer_required: true })];
const emptyAutomationData: AutomationWorkspaceData = { templates: defaultTemplates, rules: defaultRules, logs: [], workflowRuns: [], workflowEvents: [], settings: null };

export async function getAutomationWorkspaceData(organizationId: string): Promise<AutomationWorkspaceData> {
  const supabase = await createSupabaseServerClient();
  if (!supabase) return emptyAutomationData;
  const [templatesResult, rulesResult, logsResult, workflowRunsResult, workflowEventsResult, settingsResult] = await Promise.all([
    supabase.from("notice_templates").select("*").or(`organization_id.eq.${organizationId},organization_id.is.null`).order("created_at", { ascending: true }).returns<NoticeTemplateRow[]>(),
    supabase.from("notice_rules").select("*, notice_templates(template_key)").eq("organization_id", organizationId).order("created_at", { ascending: true }).returns<NoticeRuleRow[]>(),
    supabase.from("notice_logs").select("*").eq("organization_id", organizationId).order("created_at", { ascending: false }).limit(120).returns<NoticeLogRow[]>(),
    supabase.from("workflow_runs").select("*").eq("organization_id", organizationId).order("created_at", { ascending: false }).limit(12).returns<WorkflowRunRow[]>(),
    supabase.from("workflow_events").select("*").eq("organization_id", organizationId).order("created_at", { ascending: false }).limit(40).returns<WorkflowEventRow[]>(),
    supabase.from("automation_settings").select("*").eq("organization_id", organizationId).limit(1).returns<AutomationSettingsRow[]>(),
  ]);
  const templates = (templatesResult.data ?? []).map(mapTemplate);
  const rules = (rulesResult.data ?? []).map(mapRule);
  return { templates: templates.length ? templates : defaultTemplates, rules: rules.length ? rules : defaultRules, logs: (logsResult.data ?? []).map(mapLog), workflowRuns: (workflowRunsResult.data ?? []).map(mapWorkflowRun), workflowEvents: (workflowEventsResult.data ?? []).map(mapWorkflowEvent), settings: settingsResult.data?.[0] ? mapSettings(settingsResult.data[0]) : null };
}

function template(templateKey: string, category: string, noticeType: string, subject: string, body: string): NoticeTemplate { const now = new Date().toISOString(); return { id: templateKey, organizationId: null, templateKey, category, noticeType, subject, body, status: "enabled", isActive: true, timingRule: "Rule based", recipientRules: { buyer: true }, variables: noticeVariables, createdAt: now, updatedAt: now }; }
function rule(ruleKey: string, name: string, triggerType: string, timingOffset: number, templateKey: string, filters: Record<string, unknown>): NoticeRule { const now = new Date().toISOString(); return { id: ruleKey, organizationId: "system", ruleKey, name, enabled: true, isActive: true, triggerType, conditionJson: filters, timingOffset, timingUnit: "days", delayMinutes: timingOffset * 1440, templateId: templateKey, templateKey, actionType: "send_email", retryLimit: 2, recipientBehavior: "buyer", filters, createdAt: now, updatedAt: now }; }
function mapTemplate(row: NoticeTemplateRow): NoticeTemplate { return { id: row.id, organizationId: row.organization_id, templateKey: row.template_key, category: row.category ?? humanizeTemplateKey(row.template_key), noticeType: row.notice_type ?? row.template_key, subject: row.subject, body: row.body, status: row.status ?? "enabled", isActive: (row.status ?? "enabled") === "enabled", timingRule: row.timing_rule ?? "Rule based", recipientRules: row.recipient_rules ?? { buyer: true }, variables: extractVariables(row.variables), createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapRule(row: NoticeRuleRow): NoticeRule { return { id: row.id, organizationId: row.organization_id, ruleKey: row.rule_key, name: humanizeTemplateKey(row.rule_key), enabled: row.enabled, isActive: row.enabled, triggerType: row.trigger_type, conditionJson: row.filters ?? {}, timingOffset: row.timing_offset, timingUnit: row.timing_unit, delayMinutes: row.timing_unit === "days" ? row.timing_offset * 1440 : row.timing_offset, templateId: row.template_id, templateKey: row.notice_templates?.template_key ?? null, actionType: "send_email", retryLimit: 2, recipientBehavior: row.recipient_behavior, filters: row.filters ?? {}, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapLog(row: NoticeLogRow): NoticeLog { return { id: row.id, organizationId: row.organization_id, noticeType: row.notice_type, templateId: row.template_id, templateKey: null, ruleId: row.rule_id, buyerId: row.buyer_id, puppyId: row.puppy_id, relatedType: row.related_type, relatedId: row.related_id, scheduledAt: row.scheduled_at, sentAt: row.sent_at, deliveryStatus: row.delivery_status, failureReason: row.failure_reason, provider: row.provider, providerMessageId: row.provider_message_id, dedupeKey: row.dedupe_key, retryCount: 0, metadata: {}, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapWorkflowRun(row: WorkflowRunRow): WorkflowRun { return { id: row.id, organizationId: row.organization_id, runKey: row.run_key, status: row.status, startedAt: row.started_at, finishedAt: row.finished_at, summary: row.summary ?? {}, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapWorkflowEvent(row: WorkflowEventRow): WorkflowEvent { return { id: row.id, organizationId: row.organization_id, runId: row.run_id, eventKey: row.event_key, eventType: row.event_type, relatedType: row.related_type, relatedId: row.related_id, status: row.status, payload: row.payload ?? {}, createdAt: row.created_at }; }
function mapSettings(row: AutomationSettingsRow): AutomationSettings { return { id: row.id, organizationId: row.organization_id, noticesEnabled: row.notices_enabled, paymentNoticesEnabled: row.payment_notices_enabled, documentNoticesEnabled: row.document_notices_enabled, transportationNoticesEnabled: row.transportation_notices_enabled, puppyMilestoneNoticesEnabled: row.puppy_milestone_notices_enabled, providerName: row.provider_name, fromEmail: row.from_email, replyToEmail: row.reply_to_email, quietHours: row.quiet_hours ?? {}, createdAt: row.created_at, updatedAt: row.updated_at }; }
function extractVariables(value: NoticeTemplateRow["variables"]) { return Array.isArray(value) ? value.map(String) : noticeVariables; }
function humanizeTemplateKey(value: string) { return value.split(/[_-]/).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }
